@startuml MauiSlidePuzzle

class SlidePuzzleView
{
    - puzzle : SlidePuzzle
    - image : IImage
    ~ PanelViews : List<IPanelView> <<read only>>
    ~ SlidePuzzleView()
    ~ Initialize(model : SlidePuzzle) : void
    '~ ShuffleAsync(count : int) : Task
}

abstract SlidePanelView
{
    + ID : int
    + Translation : Point
    - gv : GraphicsView <<read only>>
    # SlidePanelView(image : IImage, clipRect : RectF, id : int)
    # AddTapRecognizer(tapped : Action<SlidePanelView>) : void
    {abstract} ~ DrawPanelFrame(canvas : ICanvas, clipRect : RectF) : void
    {abstract} ~ SetTappedNotifier(tapped : Action<SlidePanelView>) : void
}

class ImagePanelView
{
    ' - panel : ImagePanel
    ' - isBlank : bool
    ' ~ ImagePanelView(panel : ImagePanel)
    ' ~ SetAsBlank() : void
}

class BlankPanelView
{

}

class PanelDrawable
{
    - image : IImage <<read only>>
    - clipRect : RectF <<read only>>
    + DrawPanelFrame : Action<ICanvas, RectF>
}

class SlidePuzzle
{
    + Rows : int <<read only>>
    + Columns : int <<read only>>
    + Panels : List<SlidePanel> <<read only>>
    + BlankPanel : SlidePanel <<read only>>
    ' - panels : List<ImagePanel>
    ' - blankPanel : ImagePanel
    ~ SlidePuzzle(rows : int, columns : int)
    ~ TryMove(panel : SlidePanel) : bool
    ~ Shuffle(counts : int) : IEnumerable<SlidePanel>
}

class SlidePanel
{
    - initialLocation : Point <<read only>>
    + ID : int
    + Location : Point
    ~ SlidePanel(initialLocation : Point, id : int)
}

class SlidePuzzleController
{
    - view : SlidePuzzleView <<read only>>
    - model : SlidePuzzle <<read only>>
    - Initialize()
    - ShuffleAsync(counts : int) : void
    - PanelTapped(panelView : SlidePanelView) : void
    - ViewTapped() : void
}

class MainPage
{
    - controller : SlidePuzzleController <<read only>>
    + MainPage()
    '- InitializePuzzle() : void
}

' arrows
ImagePanelView -up-|> SlidePanelView
BlankPanelView -up-|> SlidePanelView

SlidePanelView -right-> PanelDrawable

MainPage --> SlidePuzzleView
MainPage ..> SlidePuzzle : <create> 
MainPage --> SlidePuzzleController

SlidePuzzle *.down. "many" SlidePanel
SlidePuzzleView *.down. "many" SlidePanelView

SlidePuzzleController -left-> SlidePuzzleView
SlidePuzzleController -right-> SlidePuzzle

@enduml